API_TOKEN = '1854431897:AAGxm-KEYXO9OYGbTUjLdKwTdPhxBKrh_9c'

CALL_BACKS = {
    'showcase_1': "handle_showcase",
    'section_1': 'handle_section',
    'section_2': 'handle_section',
    'section_3': 'handle_section',
    'section_4': 'handle_section',
    'goods_key_1': 'handle_goods',
    'goods_key_2': 'handle_goods',
    'goods_key_3': 'handle_goods',
    'goods_key_4': 'handle_goods',
    'goods_key_5': 'handle_goods',
    'goods_key_6': 'handle_goods',
    'goods_key_7': 'handle_goods',
    'goods_key_8': 'handle_goods',
    'goods_key_9': 'handle_goods',
    'goods_key_10': 'handle_goods',
    'goods_key_11': 'handle_goods',
    'goods_key_12': 'handle_goods',
    'back_showcase_1': 'handle_backwards',
    'back_section_1': 'handle_backwards',
    'back_section_2': 'handle_backwards',
    'back_section_3': 'handle_backwards',
    'back_section_4': 'handle_backwards',
}
