API_TOKEN = '1854431897:AAGxm-KEYXO9OYGbTUjLdKwTdPhxBKrh_9c'

CALL_BACKS = {
    'continue': "handle_continue",
    'section_1': 'handle_section_1',
    'section_2': 'handle_section_2',
    'section_3': 'handle_section_3',
    'section_4': 'handle_section_4',
    'goods_key_1': 'handle_goods_1',
    'goods_key_2': 'handle_goods_2',
    'goods_key_3': 'handle_goods_3',
    'goods_key_4': 'handle_goods_4',
    'goods_key_5': 'handle_goods_5',
    'goods_key_6': 'handle_goods_6',
    'goods_key_7': 'handle_goods_7',
    'goods_key_8': 'handle_goods_8',
    'goods_key_9': 'handle_goods_9',
    'goods_key_10': 'handle_goods_10',
    'goods_key_11': 'handle_goods_11',
    'goods_key_12': 'handle_goods_12',
    'back': 'handle_backwards',
    'back_croissant': 'handle_backwards_croissant',
    'back_pie': 'handle_backwards_pie',
    'back_pancake': 'handle_backwards_pancake',
    'back_cake': 'handle_backwards_cake',
}
